# Generated by Django 3.2.5 on 2021-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=30)),
                ('intro', models.TextField(blank=True, max_length=100)),
                ('post', models.TextField(blank=True, max_length=2000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
