# Generated by Django 3.2.5 on 2021-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='home/images'),
        ),
    ]
